### PR TITLE
Fix critical import bug and missing changelog links

### PR DESCRIPTION
**Pull request by isiahmeadows**
## Description

1. Fix a critical import bug that somehow got missed (and nobody said anything)
2. Add a couple missing changelog links.
3. Fix a slew of outdated references in the release process.
4. Get tests running on Windows. (`cmd` was running `ospec.js` in the root rather than `node_modules/.bin/ospec` due to a very unusual choice of behavior, and even `npx` wasn't sufficient to prevent that. Also, the scripts didn't fully match npm's stubs, and that caused its own set of problems on Windows.)
5. Avoid testing ospec with the repo's version, as it made the bug more difficult to test.

## Motivation and Context

Encountered this while working on Mithril after updating ospec. (I fixed it short-term by explicitly moving the dependency back a few versions.)

The plan is to release this ASAP once I confirm it either locally or via CI (hence this PR and the way the changelog is updated). Locally, I've been dealing with issues with the tests assuming a Unix system, but I don't believe this should carry over into other platforms.

## How Has This Been Tested?

Tests currently fail and I'm currently working on that, but I've verified the fix by patching the Mithril dependency manually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read all applicable contributing documents.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have updated the change log (if applicable).

### CODE REVIEW

**Comment by isiahmeadows** [comment]
Please do *not* merge this - let me merge it as I will also need to quickly turn around and cut a release.

**Comment by pygy** [comment]
Thanks for the fix @isiahmeadows 

Curious, where does the current code fail to work? `ospec` worked fine when I wrote this (with Node v13.2.x IIRC) and it still does on my machine (macOS 10.15) with node v14.15.4 and v15.5.1, and given the file name you're adding, I suppose it is Windows-related...

The `loadFromDeps` code path was there to let one use the repo as a self test harness (rather than the version in node-modules), to simulate what will happen once the new version is published.

You forgot to commit `ospec-windows-cmd-workaround` (which piques my curiosity) and the `windows-dot-bin` directory.

At last, why do the CLI tests fail to return a function? That's super weird.

**Comment by pygy** [comment]
It looks like a better fix for the windows symlink workaround would be to use https://github.com/npm/cmd-shim as a dependency.

**Comment by isiahmeadows** [comment]
> You forgot to commit ospec-windows-cmd-workaround (which piques my curiosity) and the windows-dot-bin directory.

🤦 I've updated this PR.

Also closing in favor of #30.

**Pull request closed without merging**
