### PR TITLE
update glob to v9

### PR DESCRIPTION
**Pull request by chromy**
## Description
Update glob to v9

## Motivation and Context
Installing `ospec` currently shows the following warnings:
```
 WARN  deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
 WARN  deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
```

See also:
- https://github.com/isaacs/node-glob/issues/573

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read all applicable contributing documents.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [x] I have updated the change log (if applicable).

### CODE REVIEW

**Comment by dead-claudia** [comment]
Have you tested this yet? I see the box isn't checked in the initial comment.

**Comment by dead-claudia** [comment]
@chromy Did you attach the right log file? The "before" file doesn't show failures?

**Comment by dead-claudia** [comment]
Ignore the CI run. https://github.com/MithrilJS/ospec/issues/70

**Comment by chromy** [comment]
@dead-claudia Ah by `before` I meant running the tests at HEAD (610b2c3d) and `after` was with my latest changes (bfcc9f37), sorry that was not clear.

**Comment by dead-claudia** [comment]
> @dead-claudia Ah by `before` I meant running the tests at HEAD ([610b2c3](https://github.com/MithrilJS/ospec/commit/610b2c3d21c365ee29947f8a727f6740dd04a967)) and `after` was with my latest changes ([bfcc9f3](https://github.com/MithrilJS/ospec/commit/bfcc9f37c9f087da2cd84737236cf8769f13227e)), sorry that was not clear.

@chromy Oh, okay. That makes more sense.

**Pull request merged**
